id: ID69DD84A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T15:22:41+00:00'
last_modified: '2022-06-07T18:25:42.017113+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS17500
  title: གསུང་འབུམ། ནམ་མཁའ་སེང་གེ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    EF83:
      image_group_id: I8LS17510
      title: ''
      total_pages: 679
      order: 1
      base_file: EF83.txt
    5B9A:
      image_group_id: I8LS17511
      title: ''
      total_pages: 2
      order: 2
      base_file: 5B9A.txt
    4C95:
      image_group_id: I8LS17512
      title: ''
      total_pages: 2
      order: 3
      base_file: 4C95.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
